// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.trainning.domain;

import com.spt.trainning.domain.Examine;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Examine_Roo_Configurable {
    
    declare @type: Examine: @Configurable;
    
}
